// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idcgmeemtrhjknobwxik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkY2dtZWVtdHJoamtub2J3eGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDAzNjAsImV4cCI6MjA1ODY3NjM2MH0.0h7aD3R_hkYLOtJbaZNCua4tq6A0mqMUEoHiftRIedw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);